### ISSUE TITLE
Duplicate Symbols Problem upgrading to 3.x

### ISSUE THREAD

**Issue by idsky2** [maxep/MXSegmentedPager#118]
My project works fine with MXSegmentedPager 2.0.0 but updating my Podfile to 3.0.0 or higher gives me the compile errors below.  Any suggestions?

My code just links the pager in with
# import "MXSegmentedPager.h"

I have been using an old version for a long time and want to update.  It looks like MXPagerView is getting linked twice.  pod update says:
`Removing PureLayout
Removing VGParallaxHeader
Downloading dependencies
Installing MXPagerView (0.1.3)
Installing MXParallaxHeader (0.5.2)
Installing MXSegmentedPager 3.1.0 (was 2.0.0)`
That "Installing MXPagerView (0.1.3)" is suspicious.

`duplicate symbol _OBJC_IVAR_$_MXPagerView._index in:
    /Users/bruce/Library/Developer/Xcode/DerivedData/CamperMate-flypapuedsltdegtctkdwxaxkrgs/Build/Products/Debug-iphonesimulator/MXPagerView/libMXPagerView.a(MXPagerView.o)
    /Users/bruce/Library/Developer/Xcode/DerivedData/CamperMate-flypapuedsltdegtctkdwxaxkrgs/Build/Products/Debug-iphonesimulator/libMXSegmentedPager.a(MXPagerView.o)
duplicate symbol _OBJC_CLASS_$_MXPagerView in:
    /Users/bruce/Library/Developer/Xcode/DerivedData/CamperMate-flypapuedsltdegtctkdwxaxkrgs/Build/Products/Debug-iphonesimulator/MXPagerView/libMXPagerView.a(MXPagerView.o)
    /Users/bruce/Library/Developer/Xcode/DerivedData/CamperMate-flypapuedsltdegtctkdwxaxkrgs/Build/Products/Debug-iphonesimulator/libMXSegmentedPager.a(MXPagerView.o)
duplicate symbol _OBJC_METACLASS_$_MXPagerView in:
    /Users/bruce/Library/Developer/Xcode/DerivedData/CamperMate-flypapuedsltdegtctkdwxaxkrgs/Build/Products/Debug-iphonesimulator/MXPagerView/libMXPagerView.a(MXPagerView.o)
    /Users/bruce/Library/Developer/Xcode/DerivedData/CamperMate-flypapuedsltdegtctkdwxaxkrgs/Build/Products/Debug-iphonesimulator/libMXSegmentedPager.a(MXPagerView.o)
duplicate symbol _OBJC_IVAR_$_MXPagerView._count in:
    /Users/bruce/Library/Developer/Xcode/DerivedData/CamperMate-flypapuedsltdegtctkdwxaxkrgs/Build/Products/Debug-iphonesimulator/MXPagerView/libMXPagerView.a(MXPagerView.o)
    /Users/bruce/Library/Developer/Xcode/DerivedData/CamperMate-flypapuedsltdegtctkdwxaxkrgs/Build/Products/Debug-iphonesimulator/libMXSegmentedPager.a(MXPagerView.o)
duplicate symbol _OBJC_IVAR_$_MXPagerView._pages in:
    /Users/bruce/Library/Developer/Xcode/DerivedData/CamperMate-flypapuedsltdegtctkdwxaxkrgs/Build/Products/Debug-iphonesimulator/MXPagerView/libMXPagerView.a(MXPagerView.o)
    /Users/bruce/Library/Developer/Xcode/DerivedData/CamperMate-flypapuedsltdegtctkdwxaxkrgs/Build/Products/Debug-iphonesimulator/libMXSegmentedPager.a(MXPagerView.o)
duplicate symbol _OBJC_IVAR_$_MXPagerView._registration in:
    /Users/bruce/Library/Developer/Xcode/DerivedData/CamperMate-flypapuedsltdegtctkdwxaxkrgs/Build/Products/Debug-iphonesimulator/MXPagerView/libMXPagerView.a(MXPagerView.o)
    /Users/bruce/Library/Developer/Xcode/DerivedData/CamperMate-flypapuedsltdegtctkdwxaxkrgs/Build/Products/Debug-iphonesimulator/libMXSegmentedPager.a(MXPagerView.o)
duplicate symbol _OBJC_IVAR_$_MXPagerView._reuseQueue in:
    /Users/bruce/Library/Developer/Xcode/DerivedData/CamperMate-flypapuedsltdegtctkdwxaxkrgs/Build/Products/Debug-iphonesimulator/MXPagerView/libMXPagerView.a(MXPagerView.o)
    /Users/bruce/Library/Developer/Xcode/DerivedData/CamperMate-flypapuedsltdegtctkdwxaxkrgs/Build/Products/Debug-iphonesimulator/libMXSegmentedPager.a(MXPagerView.o)
duplicate symbol _OBJC_IVAR_$_MXPagerView._transitionStyle in:
    /Users/bruce/Library/Developer/Xcode/DerivedData/CamperMate-flypapuedsltdegtctkdwxaxkrgs/Build/Products/Debug-iphonesimulator/MXPagerView/libMXPagerView.a(MXPagerView.o)
    /Users/bruce/Library/Developer/Xcode/DerivedData/CamperMate-flypapuedsltdegtctkdwxaxkrgs/Build/Products/Debug-iphonesimulator/libMXSegmentedPager.a(MXPagerView.o)
duplicate symbol _OBJC_IVAR_$_MXPagerView._dataSource in:
    /Users/bruce/Library/Developer/Xcode/DerivedData/CamperMate-flypapuedsltdegtctkdwxaxkrgs/Build/Products/Debug-iphonesimulator/MXPagerView/libMXPagerView.a(MXPagerView.o)
    /Users/bruce/Library/Developer/Xcode/DerivedData/CamperMate-flypapuedsltdegtctkdwxaxkrgs/Build/Products/Debug-iphonesimulator/libMXSegmentedPager.a(MXPagerView.o)
duplicate symbol _OBJC_CLASS_$_MXScrollView in:
    /Users/bruce/Library/Developer/Xcode/DerivedData/CamperMate-flypapuedsltdegtctkdwxaxkrgs/Build/Products/Debug-iphonesimulator/MXParallaxHeader/libMXParallaxHeader.a(MXScrollView.o)
    /Users/bruce/Library/Developer/Xcode/DerivedData/CamperMate-flypapuedsltdegtctkdwxaxkrgs/Build/Products/Debug-iphonesimulator/libMXSegmentedPager.a(MXSegmentedPager+ParallaxHeader.o)
duplicate symbol _OBJC_METACLASS_$_MXScrollView in:
    /Users/bruce/Library/Developer/Xcode/DerivedData/CamperMate-flypapuedsltdegtctkdwxaxkrgs/Build/Products/Debug-iphonesimulator/MXParallaxHeader/libMXParallaxHeader.a(MXScrollView.o)
    /Users/bruce/Library/Developer/Xcode/DerivedData/CamperMate-flypapuedsltdegtctkdwxaxkrgs/Build/Products/Debug-iphonesimulator/libMXSegmentedPager.a(MXSegmentedPager+ParallaxHeader.o)
duplicate symbol _OBJC_IVAR_$_MXScrollView._observedViews in:
    /Users/bruce/Library/Developer/Xcode/DerivedData/CamperMate-flypapuedsltdegtctkdwxaxkrgs/Build/Products/Debug-iphonesimulator/MXParallaxHeader/libMXParallaxHeader.a(MXScrollView.o)
    /Users/bruce/Library/Developer/Xcode/DerivedData/CamperMate-flypapuedsltdegtctkdwxaxkrgs/Build/Products/Debug-iphonesimulator/libMXSegmentedPager.a(MXSegmentedPager+ParallaxHeader.o)
duplicate symbol _OBJC_IVAR_$_MXScrollView._lock in:
    /Users/bruce/Library/Developer/Xcode/DerivedData/CamperMate-flypapuedsltdegtctkdwxaxkrgs/Build/Products/Debug-iphonesimulator/MXParallaxHeader/libMXParallaxHeader.a(MXScrollView.o)
    /Users/bruce/Library/Developer/Xcode/DerivedData/CamperMate-flypapuedsltdegtctkdwxaxkrgs/Build/Products/Debug-iphonesimulator/libMXSegmentedPager.a(MXSegmentedPager+ParallaxHeader.o)
duplicate symbol _OBJC_IVAR_$_MXScrollView._isObserving in:
    /Users/bruce/Library/Developer/Xcode/DerivedData/CamperMate-flypapuedsltdegtctkdwxaxkrgs/Build/Products/Debug-iphonesimulator/MXParallaxHeader/libMXParallaxHeader.a(MXScrollView.o)
    /Users/bruce/Library/Developer/Xcode/DerivedData/CamperMate-flypapuedsltdegtctkdwxaxkrgs/Build/Products/Debug-iphonesimulator/libMXSegmentedPager.a(MXSegmentedPager+ParallaxHeader.o)
ld: 14 duplicate symbols for architecture i386
`

**Comment by maxep** [comment]
Try to remove the `pods` directory and install again.

**Comment by idsky2** [comment]
Thanks @maxep! Just deleting the Pods folder fixed it. That was an easy! Upgrading fixed 2 other problems I was having too! Yay.
